# Generated by Django 3.0.2 on 2020-01-15 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_user_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='login',
            name='username',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='address',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='password',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='phone_no',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='user_type',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
