# Generated by Django 3.0.2 on 2020-01-15 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20200115_0709'),
    ]

    operations = [
        migrations.CreateModel(
            name='farm_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('crop', models.CharField(max_length=150)),
                ('quantity', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=150)),
                ('date_of_entry', models.DateField()),
            ],
        ),
    ]
