# Generated by Django 3.0.2 on 2020-01-15 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_farm_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm_details',
            name='date_of_entry',
            field=models.CharField(max_length=150),
        ),
    ]
